apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  selector:
    app: portal-noticias
  ports:
    - port: 80
      nodePort: 30000
#   targetPort: 80 #implicito quando igual
