version: '3.9'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
  alura-books:
    image: aluradocker/alura-books:1.0
    container_name: alura-books
    networks:
      - compose-bridge
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command:
      - "curl -L -X GET 'http://localhost:8080/seed' -H 'Accept: application/json'"
networks:
  compose-bridge:
    driver: bridge